# /.github/workflows/daily.yml
on:
    schedule:
      - cron:  '0 0 * * *' # every thirty minuntes
  name: Update stats periodically
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 14
        - name: Update bandwith
          run: node index.js
          env:
            token: ${{secrets.token}}